api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('usuarios/<int:pk>/', UsuarioDetail.as_view()),
    path('usuarios/', UsuarioList.as_view()),
    path('estacionamentos/<int:pk>/', EstacionamentoDetail.as_view()),
    path('estacionamentos/', EstacionamentoList.as_view()),
    path('vaga/<int:pk>/', VagaDetail.as_view()),
    path('vaga/', VagaList.as_view()),
    path('ocupacao/<int:pk>/', OcupacaoDetail.as_view()),
    path('ocupacao/', OcupacaoList.as_view()),
    path('pagamento/<int:pk>/', PagamentoDetail.as_view()),
    path('pagamento/', PagamentoList.as_view()),
]

estacioniverso/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('motorista/', include('motorista.urls')),
    path('dirigente/', include('dirigente.urls')),
    path('', include('staticpages.urls')),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),
    path('admin/', admin.site.urls),
]

motorista/urls.py
from django.urls import path

from . import views

app_name = 'motorista'
urlpatterns = [
    path('veiculos', views.list_veiculo, name='veiculos'),
    path('veiculos/create/', views.create_veiculo, name='create'),
    path('veiculos/<int:veiculo_id>/', views.detail_veiculo, name='detail'), 
    path('veiculos/delete/<int:veiculo_id>/', views.delete_veiculo, name='delete'),

    path('estacionamentos', views.list_estacionamento, name='estacionamentos'),
    path('estacionamentos/<int:estacionamento_id>/', views.detail_estacionamento, name='detailestacionamento'),

    path('estacionamentos/<int:estacionamento_id>/entrar', views.entrar_estacionamento, name='entrar'), 
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>', views.aguardar_entrada, name='aguardoentrada' ),
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>/update', views.aguardar_entrada_update, name='aguardoentradaupdate' ),
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>/recusada', views.entrada_recusada, name='entradarecusada'),

    path('estacionamentos/<int:estacionamento_id>/entrar/lotado', views.estacionamento_lotado, name='lotado'),

    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>', views.sair_estacionamento, name='sair'),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/<int:pagamento_id>', views.aguardar_saida, name='aguardosaida' ),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/update', views.aguardar_saida_update, name='aguardosaidaupdate' ),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/recusada', views.saida_recusada, name='saidarecusada'),

]

motorista/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Cor(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Marca(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class TipoVeiculo(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Veiculo(models.Model):
    dono = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete= CASCADE)
    modelo = models.CharField(max_length=255)
    placa = models.CharField(max_length=7)
    cor = models.ForeignKey(Cor, on_delete= CASCADE)
    tipo = models.ForeignKey(TipoVeiculo, on_delete= CASCADE)

    def __str__(self):
        return f'{self.marca} - {self.modelo} - {self.placa} - {self.dono}'

motorista/forms.py
from django.forms import ModelForm
from django import forms
from dirigente.models import Solicitacao
from .models import Veiculo

class VeiculoForm(ModelForm):
    class Meta:
        model = Veiculo
        fields = [
            'marca',
            'modelo',
            'placa',
            'cor',
            'tipo'
        ]
        labels = {
            'marca': "Marca",
            'modelo': "Modelo",
            'placa': "Placa",
            'cor': "Cor",
            'tipo': "Tipo"
        }

class SolicitacaoEntradaForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SolicitacaoEntradaForm, self).__init__(*args, **kwargs)
        self.fields['veiculo'] = forms.ModelChoiceField(queryset=user.veiculo_set.all(), required=True)

motorista/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from dirigente.models import *
from .forms import *

def list_veiculo(request):
    veiculo_list = request.user.veiculo_set.all()
    context = {'veiculo_list': veiculo_list}
    return render(request, 'veiculos/lista.html', context)

def detail_veiculo(request, veiculo_id):
    veiculo = get_object_or_404(Veiculo, pk=veiculo_id)
    context = {'veiculo': veiculo}
    return render(request, 'veiculos/detail.html', context)

def create_veiculo(request):
    if request.method == 'POST':
        form = VeiculoForm(request.POST)
        if form.is_valid():
            veiculo_dono = request.user
            veiculo_marca = form.cleaned_data['marca']
            veiculo_modelo = form.cleaned_data['modelo']
            veiculo_placa = form.cleaned_data['placa']
            veiculo_cor = form.cleaned_data['cor']
            veiculo_tipo = form.cleaned_data['tipo']

            veiculo = Veiculo(marca=veiculo_marca, modelo=veiculo_modelo,
                                placa = veiculo_placa, cor = veiculo_cor,
                                tipo = veiculo_tipo, dono=veiculo_dono)
            veiculo.save()
            return HttpResponseRedirect(
                reverse('motorista:detail', args=(veiculo.id, )))
    else:
        form = VeiculoForm()
    context = {'form': form}
    return render(request, 'veiculos/create.html', context)

def delete_veiculo(request, veiculo_id):
    veiculo = get_object_or_404(Veiculo, pk=veiculo_id)

    if request.method == "POST":
        veiculo.delete()
        return HttpResponseRedirect(reverse('motorista:veiculos'))

    context = {'veiculo': veiculo}
    return render(request, 'veiculos/delete.html', context)

def list_estacionamento(request):
    estacionamento_list = Estacionamento.objects.filter(aberto=True)
    ocupacao_carro_list = []
    ocupacao_moto_list = []

    for estacionamento in estacionamento_list:
        ocupacaocarro, ocupacaomoto = estacionamento.calcular_ocupacao()

        ocupacao_carro_list.append(ocupacaocarro)
        ocupacao_moto_list.append(ocupacaomoto)

    ha_estacionamento = bool(estacionamento_list)
    estacionamento_list = zip(estacionamento_list, ocupacao_carro_list, ocupacao_moto_list)

    context = {'estacionamento_list': estacionamento_list,
                'ha_estacionamentos': ha_estacionamento}

    return render(request, 'estacionamentos/lista.html', context)

def detail_estacionamento(request, estacionamento_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    ocupacaocarro, ocupacaomoto = estacionamento.calcular_ocupacao()
    context = {'estacionamento': estacionamento,
                'ocupacaocarro': ocupacaocarro,
                'ocupacaomoto': ocupacaomoto}

    return render(request, 'estacionamentos/detail.html', context)

def entrar_estacionamento(request, estacionamento_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)

    if request.method == 'POST':
        form = SolicitacaoEntradaForm(request.user, request.POST)
        if form.is_valid():
            solicitacao_veiculo = form.cleaned_data['veiculo']
            ocupacaocarro, ocupacaomoto = estacionamento.calcular_ocupacao()

            if solicitacao_veiculo.tipo.desc == "Carro" and ocupacaocarro == 100:
                return HttpResponseRedirect(reverse('motorista:lotado', args=(estacionamento.id, )))
                
            elif solicitacao_veiculo.tipo.desc == "Moto" and ocupacaomoto == 100:
                return HttpResponseRedirect(reverse('motorista:lotado', args=(estacionamento.id, )))

            solicitacao = Solicitacao(estacionamento = estacionamento, veiculo=solicitacao_veiculo)
            solicitacao.save()
            solicitacaoentrada = SolicitacaoEntrada(solicitacao=solicitacao)
            solicitacaoentrada.save()

            return HttpResponseRedirect(
                reverse('motorista:aguardoentrada', args=(estacionamento.id, solicitacao.id)))

    else:
        form = SolicitacaoEntradaForm(user=request.user)

    context = {'form': form}
    return render(request, 'estacionamentos/entrar.html', context)

def aguardar_entrada(request, estacionamento_id, solicitacao_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    
    context ={
        "tipo_solicitacao": "Entrada",
        'estacionamento': estacionamento,
        'solicitacao': solicitacao
    }
    return render(request, 'estacionamentos/aguardo.html', context)

def aguardar_entrada_update (request, estacionamento_id, solicitacao_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    solicitacaoentrada = solicitacao.solicitacaoentrada

    if solicitacaoentrada.aceita == True:
        ocupacao = solicitacaoentrada.ocupacao
        return HttpResponseRedirect(reverse('motorista:sair', args=(estacionamento.id, solicitacao.id, ocupacao.id)))

    if solicitacaoentrada.recusada == True:
        return HttpResponseRedirect(reverse('motorista:entradarecusada', args=(estacionamento.id, solicitacao.id)))
    
    context ={
        "tipo_solicitacao": "Entrada",
        'estacionamento': estacionamento,
        'solicitacao': solicitacao
    }
    return render(request, 'estacionamentos/aguardo.html', context)

def sair_estacionamento(request, estacionamento_id, solicitacao_id, ocupacao_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    ocupacao = get_object_or_404(Ocupacao, pk=ocupacao_id)

    if request.method == 'POST':
        solicitacaosaida = SolicitacaoSaida(solicitacao=solicitacao)
        solicitacaosaida.save()
        ocupacao.solicitacaosaida = solicitacaosaida
        ocupacao.save()
        pagamento = Pagamento(motorista = request.user.usuario, dirigente=estacionamento.dono.usuario,
                                ocupacao = ocupacao)

        pagamento.calcular_valor()
        pagamento.save()

        return HttpResponseRedirect(reverse('motorista:aguardosaida', args=(estacionamento.id, solicitacao.id, ocupacao.id, solicitacaosaida.id, pagamento.id)))
    else:
        context = {'vaga': ocupacao.vaga}
        return render(request, 'estacionamentos/sair.html', context)

def aguardar_saida(request, estacionamento_id, solicitacao_id, ocupacao_id, solicitacaosaida_id, pagamento_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    ocupacao = get_object_or_404(Ocupacao, pk=ocupacao_id)
    solicitacaosaida = get_object_or_404(SolicitacaoSaida, pk=solicitacaosaida_id)
    pagamento = get_object_or_404(Pagamento, pk=pagamento_id)
    
    context ={
        "tipo_solicitacao": "Saida",
        'estacionamento': estacionamento,
        'solicitacao': solicitacao,
        'ocupacao': ocupacao,
        "solicitacaosaida": solicitacaosaida,
        "pagamento" : pagamento,
    }
    return render(request, 'estacionamentos/aguardo.html', context)

def aguardar_saida_update (request, estacionamento_id, solicitacao_id, ocupacao_id, solicitacaosaida_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    solicitacaosaida = get_object_or_404(SolicitacaoSaida, pk=solicitacaosaida_id)
    ocupacao = get_object_or_404(Ocupacao, pk=ocupacao_id)
    pagamento = ocupacao.pagamento
    
    if solicitacaosaida.aceita == True:
        return HttpResponseRedirect(reverse('motorista:detailestacionamento', args=(estacionamento.id, )))

    if solicitacaosaida.recusada == True:
        return HttpResponseRedirect(reverse('motorista:saidarecusada', args=( estacionamento.id, solicitacao.id, ocupacao.id, solicitacaosaida_id)))
    
    context ={
        "tipo_solicitacao": "Saida",
        'estacionamento': estacionamento,
        'solicitacao': solicitacao,
        'ocupacao': ocupacao,
        "solicitacaosaida": solicitacaosaida,
        "pagamento" : pagamento,
    }
    return render(request, 'estacionamentos/aguardo.html', context)

def entrada_recusada(request, estacionamento_id, solicitacao_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)

    solicitacao.delete()

    context ={
        "tipo_solicitacao": "Entrada",
        'estacionamento': estacionamento,
    }

    return render(request, 'estacionamentos/recusada.html', context)

def estacionamento_lotado(request, estacionamento_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)

    context ={
        'estacionamento': estacionamento,
    }

    return render(request, 'estacionamentos/lotado.html', context)

def saida_recusada(request, estacionamento_id, solicitacao_id, ocupacao_id, solicitacaosaida_id):
    estacionamento = get_object_or_404(Estacionamento, pk=estacionamento_id)
    solicitacao = get_object_or_404(Solicitacao, pk=solicitacao_id)
    solicitacaosaida = get_object_or_404(SolicitacaoSaida, pk=solicitacaosaida_id)
    ocupacao = get_object_or_404(Ocupacao, pk=ocupacao_id)

    solicitacaosaida.delete()
    ocupacao.pagamento.delete()

    context ={
        "tipo_solicitacao": "Saida",
        'estacionamento': estacionamento,
        'solicitacao': solicitacao,
        'ocupacao':ocupacao
    }

    return render(request, 'estacionamentos/recusada.html', context)

motorista/templates/estacionamentos/aguardo.html
{% extends 'baselocked.html' %}

{% block title %}
Aguardando resposta
{% endblock title %}

{% block content %}
<div class="center">
{% if tipo_solicitacao == "Entrada" %}
<h2>Aguarde sua solicitação ser aceita</h2>
{% elif tipo_solicitacao == "Saida" %}
<h2>Realize o pagamento de R${{ pagamento.valor }} para a Chave PiX {{pagamento.dirigente.chavepix}} e aguarde sua solicitação ser aceita</h2>
{% endif %}
<img src="https://i.imgur.com/Wb5Jlza.gif" width="250">
{% if tipo_solicitacao == "Entrada" %}
    <a href="{% url 'motorista:aguardoentradaupdate' estacionamento.id solicitacao.id %}"><button>Atualizar</button></a>
    {% elif tipo_solicitacao == "Saida" %}
    <a href="{% url 'motorista:aguardosaidaupdate' estacionamento.id solicitacao.id ocupacao.id solicitacaosaida.id %}"><button>Atualizar</button></a>
    {% endif %}

</div>
{% endblock content %} 

motorista/templates/estacionamentos/detail.html
{% extends 'base.html' %}

{% block title %}
{{ estacionamento.nome }}
{% endblock title %}

{% block content %}

<h2>Detalhes do estacionamento </h2>

<div class="motorista-sup">
    <h2><b>{{ estacionamento.nome }}</b> - <i>{{ estacionamento.endereco }}</i></h2>

    
</div>

<div class="motorista-sup">
    <section class="dados-de-veiculo">
        
        <img src="https://seeklogo.com/images/P/parking-black-white-sign-logo-EF735C1713-seeklogo.com.png">

        <ul>
            <li><b>Nome:</b> {{ estacionamento.nome }}</li>
            <li><b>Endereço:</b> {{ estacionamento.endereco }}</li>
            <li><b>Preço da primeira hora:</b> R${{ estacionamento.preco1h }}</li>
            <li><b>Preço por hora adicional:</b> R${{ estacionamento.precoHoraAdicional }}</li>
            <li><b>Preço da diária:</b> R${{ estacionamento.precoDiaria }}</li>
            <li><b>Ocupação para Carros:</b> {{ ocupacaocarro }}%</li>
            <li><b>Ocupação para Motos:</b> {{ ocupacaomoto }}%</li>
        </ul>
        
    </section>
    <div class='options'>
        {{ form.as_p }}
        <a href="{% url 'motorista:entrar' estacionamento.id %}"><button>Solicitar entrada</button></a>
    </div>
</div>
{% endblock content %}

motorista/templates/estacionamentos/entrar.html
{% extends 'base.html' %}

{% block title %}
Solicitar entrada
{% endblock title %}

{% block content %}
<div class="center">
<h2>Solicitar entrada</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Solicitar</button>
</form>
</div>
{% endblock content %} 

motorista/templates/estacionamentos/lista.html
{% extends 'base.html' %}

{% block title %}
Todos os estacionamentos
{% endblock title %}

{% block content %}
<h2>Todos os estacionamentos</h2>
{% if ha_estacionamentos %}
<section class="lista-de-cards">
    {% for estacionamento, ocupacaocarro, ocupacaomoto in estacionamento_list %}

    <article class="card">
        <a href="{% url 'motorista:detailestacionamento' estacionamento.id %}">

        <img src="https://seeklogo.com/images/P/parking-black-white-sign-logo-EF735C1713-seeklogo.com.png">

        </a>
        <h3><b>{{ estacionamento.nome }}</b></h3>
        <p><i>{{ estacionamento.endereco }}</i></p>
        <p><b>Ocupação para Carros:</b> {{ ocupacaocarro }}%</p>
        <p><b>Ocupação para Motos:</b> {{ ocupacaomoto }}%</p>
        
    </article>

    {% endfor %}
</section>
{% else %}
<p>Nenhum estacionamento aberto foi encontrado</p>
{% endif %}

{% endblock content %}

motorista/templates/estacionamentos/sair.html
{% extends 'baselocked.html' %}

{% block title %}
Estacionado
{% endblock title %}

{% block content %}
<div class="center">
<h2>Estacione na vaga Nº {{ vaga.numero }}.</h2>
<h3>Tenha um bom dia!</h3>

<img class="margem" src="https://pic.onlinewebfonts.com/svg/img_254747.png" width="250" >

<form method="post">
    {% csrf_token %}
    <button type="submit">Solicitar saída</button>
</form>
</div>
{% endblock content %} 