api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('usuarios/<int:pk>/', UsuarioDetail.as_view()),
    path('usuarios/', UsuarioList.as_view()),
    path('estacionamentos/<int:pk>/', EstacionamentoDetail.as_view()),
    path('estacionamentos/', EstacionamentoList.as_view()),
    path('vaga/<int:pk>/', VagaDetail.as_view()),
    path('vaga/', VagaList.as_view()),
    path('ocupacao/<int:pk>/', OcupacaoDetail.as_view()),
    path('ocupacao/', OcupacaoList.as_view()),
    path('pagamento/<int:pk>/', PagamentoDetail.as_view()),
    path('pagamento/', PagamentoList.as_view()),
]

dirigente/urls.py
from django.urls import path

from . import views

app_name = 'dirigente'
urlpatterns = [
    path('estacionamento/create/', views.create_estacionamento, name='create'),
    path('estacionamento', views.detail_estacionamento, name='detail'), 
    path('estacionamento/atualizar', views.atualizar_estacionamento, name='atualizar'),
    path('estacionamento/delete/', views.delete_estacionamento, name='delete'),
    path('estacionamento/abrir', views.abrir_estacionamento, name='abrir'),
    path('estacionamento/fechar', views.fechar_estacionamento, name='fechar'),
    path('estacionamento/aceitarentrada/<int:solicitacao_id>', views.aceitar_entrada, name='aceitarentrada'),
    path('estacionamento/recusarentrada/<int:solicitacao_id>', views.recusar_entrada, name='recusarentrada'),
    path('estacionamento/aceitarsaida/<int:solicitacao_id>', views.aceitar_saida, name='aceitarsaida'),
    path('estacionamento/recusarsaida/<int:solicitacao_id>', views.recusar_saida, name='recusarsaida'),
]

estacioniverso/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('motorista/', include('motorista.urls')),
    path('dirigente/', include('dirigente.urls')),
    path('', include('staticpages.urls')),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),
    path('admin/', admin.site.urls),
]

motorista/urls.py
from django.urls import path

from . import views

app_name = 'motorista'
urlpatterns = [
    path('veiculos', views.list_veiculo, name='veiculos'),
    path('veiculos/create/', views.create_veiculo, name='create'),
    path('veiculos/<int:veiculo_id>/', views.detail_veiculo, name='detail'), 
    path('veiculos/delete/<int:veiculo_id>/', views.delete_veiculo, name='delete'),

    path('estacionamentos', views.list_estacionamento, name='estacionamentos'),
    path('estacionamentos/<int:estacionamento_id>/', views.detail_estacionamento, name='detailestacionamento'),

    path('estacionamentos/<int:estacionamento_id>/entrar', views.entrar_estacionamento, name='entrar'), 
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>', views.aguardar_entrada, name='aguardoentrada' ),
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>/update', views.aguardar_entrada_update, name='aguardoentradaupdate' ),
    path('estacionamentos/<int:estacionamento_id>/entrar/<int:solicitacao_id>/recusada', views.entrada_recusada, name='entradarecusada'),

    path('estacionamentos/<int:estacionamento_id>/entrar/lotado', views.estacionamento_lotado, name='lotado'),

    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>', views.sair_estacionamento, name='sair'),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/<int:pagamento_id>', views.aguardar_saida, name='aguardosaida' ),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/update', views.aguardar_saida_update, name='aguardosaidaupdate' ),
    path('estacionamentos/<int:estacionamento_id>/sair/<int:solicitacao_id>/<int:ocupacao_id>/<int:solicitacaosaida_id>/recusada', views.saida_recusada, name='saidarecusada'),

]

dirigente/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields.related import OneToOneField
from django.contrib.auth.models import User
from motorista.models import Veiculo
from accounts.models import Usuario

class TipoVaga(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Estacionamento(models.Model):
    dono = OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    aberto = models.BooleanField(default=False)
    preco1h = models.FloatField()
    precoHoraAdicional = models.FloatField()
    precoDiaria = models.FloatField()
    vagasCarro = models.IntegerField()
    vagasMoto = models.IntegerField()

    def calcular_ocupacao(self):
        vagasocupadas = self.vaga_set.filter(ocupada=True)

        vagascarro = self.vaga_set.filter(tipo=1)
        numvagascarro = vagascarro.count()

        if numvagascarro:

            vagasocupadascarro = vagasocupadas.filter(tipo=1)
            numvagasocupadascarro = vagasocupadascarro.count()

            ocupacaocarro = 100*numvagasocupadascarro/numvagascarro
        
        else:
            ocupacaocarro = 100

        vagasmoto = self.vaga_set.filter(tipo=2)
        numvagasmoto = vagasmoto.count()

        if numvagasmoto:

            vagasocupadasmoto = vagasocupadas.filter(tipo=2)
            numvagasocupadasmoto = vagasocupadasmoto.count()

            ocupacaomoto = 100*numvagasocupadasmoto/numvagasmoto
        
        else:
            ocupacaomoto = 100

        return (ocupacaocarro, ocupacaomoto)

    def __str__(self):
        return f'{self.nome}'

class Vaga(models.Model):
    numero = models.IntegerField()
    estacionamento = models.ForeignKey(Estacionamento, on_delete=CASCADE)
    tipo = models.ForeignKey(TipoVaga, on_delete=CASCADE)
    ocupada=models.BooleanField(default=False)

    def __str__(self):
        return f'{self.estacionamento.nome} - {self.numero}'

class Solicitacao(models.Model):
    estacionamento = models.ForeignKey(Estacionamento, on_delete=CASCADE)
    veiculo = models.ForeignKey(Veiculo, on_delete=CASCADE)

    def __str__(self):
        return f'{self.estacionamento.nome} - {self.veiculo.marca} - {self.veiculo.modelo}'

class SolicitacaoEntrada(models.Model):
    solicitacao = models.OneToOneField(Solicitacao, on_delete=CASCADE)
    aceita = models.BooleanField(default=False)
    horaAceitacao = models.DateTimeField(auto_now=True)
    recusada = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.solicitacao}'

class SolicitacaoSaida(models.Model):
    solicitacao = models.OneToOneField(Solicitacao, on_delete=CASCADE)
    aceita = models.BooleanField(default=False)
    horaAceitacao = models.DateTimeField(auto_now=True)
    recusada = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.solicitacao}'

class Ocupacao(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=CASCADE)
    vaga = models.ForeignKey(Vaga, on_delete=CASCADE)
    solicitacaoentrada = models.OneToOneField(SolicitacaoEntrada, on_delete=CASCADE)
    solicitacaosaida = models.OneToOneField(SolicitacaoSaida, on_delete=SET_NULL, blank=True, null=True)
    ativa = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.veiculo} - {self.vaga}'

class Pagamento(models.Model):
    motorista = models.ForeignKey(Usuario,
                               on_delete=CASCADE, related_name='pagamentos')
    dirigente = models.ForeignKey(Usuario,
                               on_delete=CASCADE, related_name='recebimentos')
    ocupacao = models.OneToOneField(Ocupacao, on_delete=CASCADE)
    valor = models.FloatField(blank=True, null=True)
    concluido = models.BooleanField(default=False)

    def calcular_valor(self):
        estacionamento = self.ocupacao.vaga.estacionamento
        tempo = (self.ocupacao.solicitacaosaida.horaAceitacao-self.ocupacao.solicitacaoentrada.horaAceitacao).seconds
        numhoras = (tempo // 3600)
        numdias = numhoras // 24
        numhoras = numhoras - 24*numdias

        self.valor = estacionamento.preco1h + estacionamento.precoHoraAdicional*numhoras + estacionamento.precoDiaria*numdias

        return self.valor

    def __str__(self):
        return f'{self.motorista} -> {self.dirigente} - R${self.valor}'

motorista/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Cor(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Marca(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class TipoVeiculo(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Veiculo(models.Model):
    dono = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete= CASCADE)
    modelo = models.CharField(max_length=255)
    placa = models.CharField(max_length=7)
    cor = models.ForeignKey(Cor, on_delete= CASCADE)
    tipo = models.ForeignKey(TipoVeiculo, on_delete= CASCADE)

    def __str__(self):
        return f'{self.marca} - {self.modelo} - {self.placa} - {self.dono}'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Estacioniverso
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <img src="https://i.imgur.com/jF63zLX.png" width="300">
        </a>
        <nav id="navegacao-principal">
            <ul>
            {% if user.is_authenticated %}
                <li> Logado como <b> {{ user.username }} </b> </li>
            {% endif %}
            {% if perms.motorista.view_veiculo %}
                <li><a href="{% url 'motorista:estacionamentos' %}">Lista de estacionamentos</a></li>
                <li><a href="{% url 'motorista:veiculos' %}">Meus Veículos</a></li>
            {% endif %}
            {% if perms.dirigente.view_estacionamento %}
                <li><a href="{% url 'dirigente:detail' %}">Meu estacionamento</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Log out</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}
            </ul>
        </nav>

    </header>
    <hr>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

templates/baselocked.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Estacioniverso
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <img src="https://i.imgur.com/jF63zLX.png" width="300">
        <nav id="navegacao-principal">
            <ul>
            {% if user.is_authenticated %}
                <li> Logado como <b> {{ user.username }} </b> </li>
            {% endif %}
            </ul>
        </nav>

    </header>
    <hr>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
    <img src="https://media.istockphoto.com/vectors/underground-car-parking-vector-id534195116?k=20&m=534195116&s=612x612&w=0&h=MI1I5w2Nb-QThet9UTfI4pG9XfqAbQakK6Vwd8yfYhU=" width=1240>
{% endblock content %}