api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('usuarios/<int:pk>/', UsuarioDetail.as_view()),
    path('usuarios/', UsuarioList.as_view()),
    path('estacionamentos/<int:pk>/', EstacionamentoDetail.as_view()),
    path('estacionamentos/', EstacionamentoList.as_view()),
    path('vaga/<int:pk>/', VagaDetail.as_view()),
    path('vaga/', VagaList.as_view()),
    path('ocupacao/<int:pk>/', OcupacaoDetail.as_view()),
    path('ocupacao/', OcupacaoList.as_view()),
    path('pagamento/<int:pk>/', PagamentoDetail.as_view()),
    path('pagamento/', PagamentoList.as_view()),
]

dirigente/urls.py
from django.urls import path

from . import views

app_name = 'dirigente'
urlpatterns = [
    path('estacionamento/create/', views.create_estacionamento, name='create'),
    path('estacionamento', views.detail_estacionamento, name='detail'), 
    path('estacionamento/atualizar', views.atualizar_estacionamento, name='atualizar'),
    path('estacionamento/delete/', views.delete_estacionamento, name='delete'),
    path('estacionamento/abrir', views.abrir_estacionamento, name='abrir'),
    path('estacionamento/fechar', views.fechar_estacionamento, name='fechar'),
    path('estacionamento/aceitarentrada/<int:solicitacao_id>', views.aceitar_entrada, name='aceitarentrada'),
    path('estacionamento/recusarentrada/<int:solicitacao_id>', views.recusar_entrada, name='recusarentrada'),
    path('estacionamento/aceitarsaida/<int:solicitacao_id>', views.aceitar_saida, name='aceitarsaida'),
    path('estacionamento/recusarsaida/<int:solicitacao_id>', views.recusar_saida, name='recusarsaida'),
]

estacioniverso/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('motorista/', include('motorista.urls')),
    path('dirigente/', include('dirigente.urls')),
    path('', include('staticpages.urls')),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),
    path('admin/', admin.site.urls),
]

dirigente/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields.related import OneToOneField
from django.contrib.auth.models import User
from motorista.models import Veiculo
from accounts.models import Usuario

class TipoVaga(models.Model):
    desc=models.CharField(max_length=255)

    def __str__(self):
        return f'{self.desc}'

class Estacionamento(models.Model):
    dono = OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    aberto = models.BooleanField(default=False)
    preco1h = models.FloatField()
    precoHoraAdicional = models.FloatField()
    precoDiaria = models.FloatField()
    vagasCarro = models.IntegerField()
    vagasMoto = models.IntegerField()

    def calcular_ocupacao(self):
        vagasocupadas = self.vaga_set.filter(ocupada=True)

        vagascarro = self.vaga_set.filter(tipo=1)
        numvagascarro = vagascarro.count()

        if numvagascarro:

            vagasocupadascarro = vagasocupadas.filter(tipo=1)
            numvagasocupadascarro = vagasocupadascarro.count()

            ocupacaocarro = 100*numvagasocupadascarro/numvagascarro
        
        else:
            ocupacaocarro = 100

        vagasmoto = self.vaga_set.filter(tipo=2)
        numvagasmoto = vagasmoto.count()

        if numvagasmoto:

            vagasocupadasmoto = vagasocupadas.filter(tipo=2)
            numvagasocupadasmoto = vagasocupadasmoto.count()

            ocupacaomoto = 100*numvagasocupadasmoto/numvagasmoto
        
        else:
            ocupacaomoto = 100

        return (ocupacaocarro, ocupacaomoto)

    def __str__(self):
        return f'{self.nome}'

class Vaga(models.Model):
    numero = models.IntegerField()
    estacionamento = models.ForeignKey(Estacionamento, on_delete=CASCADE)
    tipo = models.ForeignKey(TipoVaga, on_delete=CASCADE)
    ocupada=models.BooleanField(default=False)

    def __str__(self):
        return f'{self.estacionamento.nome} - {self.numero}'

class Solicitacao(models.Model):
    estacionamento = models.ForeignKey(Estacionamento, on_delete=CASCADE)
    veiculo = models.ForeignKey(Veiculo, on_delete=CASCADE)

    def __str__(self):
        return f'{self.estacionamento.nome} - {self.veiculo.marca} - {self.veiculo.modelo}'

class SolicitacaoEntrada(models.Model):
    solicitacao = models.OneToOneField(Solicitacao, on_delete=CASCADE)
    aceita = models.BooleanField(default=False)
    horaAceitacao = models.DateTimeField(auto_now=True)
    recusada = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.solicitacao}'

class SolicitacaoSaida(models.Model):
    solicitacao = models.OneToOneField(Solicitacao, on_delete=CASCADE)
    aceita = models.BooleanField(default=False)
    horaAceitacao = models.DateTimeField(auto_now=True)
    recusada = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.solicitacao}'

class Ocupacao(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=CASCADE)
    vaga = models.ForeignKey(Vaga, on_delete=CASCADE)
    solicitacaoentrada = models.OneToOneField(SolicitacaoEntrada, on_delete=CASCADE)
    solicitacaosaida = models.OneToOneField(SolicitacaoSaida, on_delete=SET_NULL, blank=True, null=True)
    ativa = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.veiculo} - {self.vaga}'

class Pagamento(models.Model):
    motorista = models.ForeignKey(Usuario,
                               on_delete=CASCADE, related_name='pagamentos')
    dirigente = models.ForeignKey(Usuario,
                               on_delete=CASCADE, related_name='recebimentos')
    ocupacao = models.OneToOneField(Ocupacao, on_delete=CASCADE)
    valor = models.FloatField(blank=True, null=True)
    concluido = models.BooleanField(default=False)

    def calcular_valor(self):
        estacionamento = self.ocupacao.vaga.estacionamento
        tempo = (self.ocupacao.solicitacaosaida.horaAceitacao-self.ocupacao.solicitacaoentrada.horaAceitacao).seconds
        numhoras = (tempo // 3600)
        numdias = numhoras // 24
        numhoras = numhoras - 24*numdias

        self.valor = estacionamento.preco1h + estacionamento.precoHoraAdicional*numhoras + estacionamento.precoDiaria*numdias

        return self.valor

    def __str__(self):
        return f'{self.motorista} -> {self.dirigente} - R${self.valor}'

dirigente/forms.py
from django.forms import ModelForm
from .models import Estacionamento

class EstacionamentoForm(ModelForm):
    class Meta:
        model = Estacionamento
        fields = [
            'nome',
            'endereco',
            'preco1h',
            'precoHoraAdicional',
            'precoDiaria',
            'vagasCarro',
            'vagasMoto'
        ]
        labels = {
            'nome': "Nome",
            'endereco': "Endereço",
            'preco1h': "Preço da primeira hora",
            'precoHoraAdicional': "Preço por hora adicional",
            'precoDiaria': "Preço da diária",
            'vagasCarro': "Número de vagas para carro",
            'vagasMoto': "Número de vagas para motocicletas",
        }

dirigente/views.py
from django.db.models.fields import NullBooleanField
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from .forms import *

def detail_estacionamento(request):
    ocupacaocarro = None
    ocupacaomoto = None
    lista_ocupacao = None
    lista_pagamentos = None
    lista_solicitacoes_entrada = None
    lista_solicitacoes_saida = None
    valor_total = None
    try:
        estacionamento = request.user.estacionamento

        ocupacaocarro, ocupacaomoto = estacionamento.calcular_ocupacao()

        lista_ocupacao = []

        lista_vagas = request.user.estacionamento.vaga_set.filter(ocupada=True)

        lista_pagamentos= request.user.usuario.recebimentos.filter(concluido=True)
        valor_total = 0

        lista_solicitacoes = estacionamento.solicitacao_set.all()
        lista_solicitacoes_entrada = []
        lista_solicitacoes_saida = []

        for vaga in lista_vagas:
            lista_ocupacao.append(vaga.ocupacao_set.filter(ativa=True)[0])
        
        for pagamento in lista_pagamentos:
            valor_total += pagamento.valor

        for solicitacao in lista_solicitacoes:
            if solicitacao.solicitacaoentrada.aceita == False and solicitacao.solicitacaoentrada.recusada == False:
                lista_solicitacoes_entrada.append(solicitacao.solicitacaoentrada)

        try:
            if solicitacao.solicitacaosaida.aceita == False and solicitacao.solicitacaosaida.recusada == False:
                lista_solicitacoes_saida.append(solicitacao.solicitacaosaida)
        except:
            pass
    except:
        estacionamento = None
    
    context = {'estacionamento': estacionamento,
                'ocupacaocarro': ocupacaocarro,
                'ocupacaomoto': ocupacaomoto,
                'lista_ocupacao': lista_ocupacao,
                'lista_pagamentos': lista_pagamentos,
                'lista_solicitacoes_saida': lista_solicitacoes_saida,
                'lista_solicitacoes_entrada': lista_solicitacoes_entrada,
                'valor_total':valor_total
                }
    return render(request, 'estacionamento/detail.html', context)

def create_estacionamento(request):
    if request.method == 'POST':
        form = EstacionamentoForm(request.POST)
        if form.is_valid():
            estacionamento_dono = request.user
            estacionamento_nome = form.cleaned_data['nome']
            estacionamento_endereco = form.cleaned_data['endereco']
            estacionamento_preco1h = form.cleaned_data['preco1h']
            estacionamento_precoHoraAdicional = form.cleaned_data['precoHoraAdicional']
            estacionamento_precoDiaria = form.cleaned_data['precoDiaria']
            estacionamento_vagasCarro = form.cleaned_data['vagasCarro']
            estacionamento_vagasMoto = form.cleaned_data['vagasMoto']

            estacionamento = Estacionamento(nome=estacionamento_nome, endereco=estacionamento_endereco,
                                preco1h = estacionamento_preco1h, precoHoraAdicional = estacionamento_precoHoraAdicional,
                                precoDiaria = estacionamento_precoDiaria, dono=estacionamento_dono,
                                vagasCarro = estacionamento_vagasCarro, vagasMoto=estacionamento_vagasMoto)
            estacionamento.save()

            if estacionamento_vagasCarro:
                for i in range(estacionamento_vagasCarro):
                    vaga = Vaga(numero = i+1, estacionamento=estacionamento, tipo=TipoVaga.objects.get(desc="Carro"))
                    vaga.save()

            if estacionamento_vagasMoto:
                for i in range(estacionamento_vagasMoto):
                    vaga = Vaga(numero = i+estacionamento_vagasCarro+1, estacionamento=estacionamento, tipo=TipoVaga.objects.get(desc="Moto"))
                    vaga.save()

            return HttpResponseRedirect(
                reverse('dirigente:detail'))
    else:
        form = EstacionamentoForm()
    context = {'form': form}
    return render(request, 'estacionamento/create.html', context)

def atualizar_estacionamento(request):
    return HttpResponseRedirect(
                reverse('dirigente:detail'))

def aceitar_entrada(request, solicitacao_id):
    solicitacao = get_object_or_404(SolicitacaoEntrada, pk=solicitacao_id)
    estacionamento = request.user.estacionamento

    if solicitacao.solicitacao.veiculo.tipo.desc == "Carro":
        vaga = estacionamento.vaga_set.filter(ocupada=False, tipo=1)[0]
    if solicitacao.solicitacao.veiculo.tipo.desc == "Moto":
        vaga = estacionamento.vaga_set.filter(ocupada=False, tipo=2)[0]

    solicitacao.aceita = True
    solicitacao.save()

    ocupacao = Ocupacao(veiculo=solicitacao.solicitacao.veiculo, vaga=vaga, 
                        solicitacaoentrada=solicitacao,
                        ativa=True)

    ocupacao.save()
    vaga.ocupada = True
    vaga.save()

    return HttpResponseRedirect(
        reverse('dirigente:detail'))
    
def recusar_entrada(request, solicitacao_id):
    solicitacao = get_object_or_404(SolicitacaoEntrada, pk=solicitacao_id)

    solicitacao.recusada = True
    solicitacao.save()

    return HttpResponseRedirect(
        reverse('dirigente:detail'))

def aceitar_saida(request,solicitacao_id, ):
    solicitacao = get_object_or_404(SolicitacaoSaida, pk=solicitacao_id)
    ocupacao = solicitacao.ocupacao
    vaga = ocupacao.vaga
    pagamento = ocupacao.pagamento

    solicitacao.aceita = True
    solicitacao.save()

    ocupacao.ativa = False
    ocupacao.save()

    pagamento.concluido = True
    pagamento.save()

    vaga.ocupada = False
    vaga.save()

    return HttpResponseRedirect(
        reverse('dirigente:detail'))

def recusar_saida(request,solicitacao_id):
    solicitacao = get_object_or_404(SolicitacaoSaida, pk=solicitacao_id)

    solicitacao.recusada = True
    solicitacao.save()

    return HttpResponseRedirect(
        reverse('dirigente:detail'))

def abrir_estacionamento(request):
    estacionamento = request.user.estacionamento
    estacionamento.aberto = True
    estacionamento.save()

    return HttpResponseRedirect(
                reverse('dirigente:detail'))

def fechar_estacionamento(request):
    estacionamento = request.user.estacionamento
    estacionamento.aberto = False
    estacionamento.save()

    return HttpResponseRedirect(
                reverse('dirigente:detail'))

def delete_estacionamento(request):
    estacionamento = request.user.estacionamento

    if request.method == "POST":
        estacionamento.delete()
        return HttpResponseRedirect(reverse('index'))

    context = {'estacionamento': estacionamento}
    return render(request, 'estacionamento/delete.html', context)

dirigente/templates/estacionamento/create.html
{% extends 'base.html' %}

{% block title %}
Criar Estacionamento
{% endblock title %}

{% block content %}
<h2>Criar seu estacionamento</h2>
<form method="POST" action="{% url 'dirigente:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

dirigente/templates/estacionamento/delete.html
{% extends 'base.html' %}

{% block title %}
Apagar estacionamento
{% endblock title %}

{% block content %}
<form action="{% url 'dirigente:delete' %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o estacionamento <b>"{{ estacionamento.nome }}"</b>?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

dirigente/templates/estacionamento/detail.html
{% extends 'base.html' %}

{% block title %}
Meu estacionamento
{% endblock title %}

{% block content %}
<div class="dirigente-sup">
  <div><h1>Meu estacionamento</h1></div>
  {% if estacionamento %}
  <div>
    <a href="{% url 'dirigente:atualizar' %}"><button>Atualizar</button></a>
    {% if estacionamento.aberto %}
    <a href="{% url 'dirigente:fechar' %}"><button class="vermelho">Fechar</button></a>
    {% else %}
    <a href="{% url 'dirigente:abrir' %}"><button>Abrir</button></a>
    {% endif %}
    <a href="{% url 'dirigente:delete' %}"><button class="vermelho">Apagar</button></a>
  </div>
  {% endif %}
</div>

{% if estacionamento %}
<h2>{{ estacionamento.nome }} - <i>{{ estacionamento.endereco }}</i></h2>
<p><b>Ocupação para Carros:</b> {{ ocupacaocarro }}% | <b>Ocupação para Motos:</b> {{ ocupacaomoto }}%</p>
<div class="dirigente-sup">
  <div>
    <h4>Ocupação</h4>
    <table class="styled-table">
        <tr>
          <th> Vaga </th>
          <th> Tipo </th>
          <th> Placa </th>
          <th> Marca </th>
          <th> Modelo </th>
          <th> Motorista </th>
          <th> Chegada </th>
        </tr>
        {% for ocupacao in lista_ocupacao %}
        <tr>
          <td>{{ ocupacao.vaga.numero }}</td>
          <td>{{ ocupacao.veiculo.tipo.desc }}</td>
          <td>{{ ocupacao.veiculo.placa }}</td>
          <td>{{ ocupacao.veiculo.marca }}</td>
          <td>{{ ocupacao.veiculo.modelo }}</td>
          <td>{{ ocupacao.veiculo.dono.username}}</td>
          <td>{{ ocupacao.solicitacaoentrada.horaAceitacao | time }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
    </table>
  </div>

  <div>
    <h4>Histórico de contas</h4>
    <table class="styled-table">
      <tr>
        <th> Motorista </th>
        <th> Chegada </th>
        <th> Saída </th>
        <th> Valor </th>
      </tr>
      {% for pagamento in lista_pagamentos %}
      <tr>
        <td>{{ pagamento.motorista.djangouser.username }}</td>
        <td>{{ pagamento.ocupacao.solicitacaoentrada.horaAceitacao | time }}</td>
        <td>{{ pagamento.ocupacao.solicitacaosaida.horaAceitacao | time }}</td>
        <td>R${{ pagamento.valor }}</td>
      </tr>
      {% endfor %}
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </table>
    <div class="dirigente-sup">
      <h4>Valor total recebido:</h4>
      <h3 class="verde">R${{ valor_total }}</h3>
    </div>
  </div>
</div>

<div class="dirigente-sup">
  <div>
    <h4>Solicitações de entrada</h4>
    <table class="styled-table">
        <tr>
          <th> Tipo </th>
          <th> Placa </th>
          <th> Marca </th>
          <th> Modelo </th>
          <th></th>
          <th></th>
        </tr>
        {% for solicitacao in lista_solicitacoes_entrada %}
        <tr>
          <td>{{ solicitacao.solicitacao.veiculo.tipo }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.placa }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.marca }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.modelo }}</td>
          <td><a href="{% url 'dirigente:aceitarentrada' solicitacao.id %}"><b>Aceitar</b></a></td>
          <td><a href="{% url 'dirigente:recusarentrada' solicitacao.id %}"><b>Recusar</b></a></td>
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
    </table>
  </div>

  <div>
    <h4>Solicitações de saída</h4>
    <p>Só aceite a solicitação após o recebimento do pagamento</p>
    <table class="styled-table">
        <tr>
          <th> Tipo </th>
          <th> Placa </th>
          <th> Marca </th>
          <th> Modelo </th>
          <th> Valor </th>
          <th></th>
          <th></th>
        </tr>
        {% for solicitacao in lista_solicitacoes_saida %}
        <tr>
          <td>{{ solicitacao.solicitacao.veiculo.tipo }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.placa }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.marca }}</td>
          <td>{{ solicitacao.solicitacao.veiculo.modelo }}</td>
          <td>R${{ solicitacao.ocupacao.pagamento.valor }}</td>
          <td><a href="{% url 'dirigente:aceitarsaida' solicitacao.id %}"><b>Aceitar</b></a></td>
          <td><a href="{% url 'dirigente:recusarsaida' solicitacao.id %}"><b>Recusar</b></a></td>
        </tr>
        {% endfor %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
    </table>
  </div>
</div>

{% else %}
<p>Você ainda não possui um estacionamento cadastrado</p>

{% if perms.dirigente.add_estacionamento %}
    <a href="{% url 'dirigente:create' %}"><button type="submit">Criar seu estacionamento</button></a>
{% endif %}
{% endif %}

{% endblock content %}